obj-m := oh_my_first_driver.o
obj-m += init.o
obj-m += exit.o

obj-m := init_exit.o
init_exit-objs := init.o exit.o 



obj-m := oh_my_first_driver.o
obj-m += template_driver.o

obj-m := exporting_symbol.o
obj-m += using_symbol.o

obj-m := parameters.o
obj-m := char_drv.o

obj-m := block_drv.o

obj-m := memory_alloc_kernel.o 
